# Generated by Django 2.0.8 on 2020-02-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='out_time',
            field=models.DateField(blank=True, null=True, verbose_name='离开时间'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
