# Generated by Django 2.0.8 on 2020-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20200215_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='parking_status',
            field=models.CharField(choices=[(1, '停车中'), (0, '已离开')], default=1, max_length=10, verbose_name='停车状态'),
        ),
    ]
