# Generated by Django 2.0.8 on 2020-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20200215_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='parking_status',
            field=models.CharField(choices=[('in', '停车中'), ('out', '已离开')], default='in', max_length=10, verbose_name='停车状态'),
        ),
    ]
