# Generated by Django 2.0.8 on 2020-02-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_charge_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='status',
        ),
        migrations.AlterField(
            model_name='charge',
            name='pay_level_1',
            field=models.IntegerField(verbose_name='第一时段1-5小时'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='pay_level_2',
            field=models.IntegerField(verbose_name='第二时段5-12小时'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='pay_level_3',
            field=models.IntegerField(verbose_name='第三时段12-24小时'),
        ),
    ]
